<?php

use Well35\EnumObjects\EnumObjects;

it('generates one file per enum, mirroring nested namespaces into directories', function () {
    $this->artisan('enum-objects:generate')->assertExitCode(0);

    expect(file_exists($this->outputDir.'/BrowseSort.ts'))->toBeTrue()
        ->and(file_exists($this->outputDir.'/Priority.ts'))->toBeTrue()
        ->and(file_exists($this->outputDir.'/Suit.ts'))->toBeTrue()
        ->and(file_exists($this->outputDir.'/ItemRarity.ts'))->toBeTrue()
        ->and(file_exists($this->outputDir.'/Items/ItemSlot.ts'))->toBeTrue()
        ->and(file_exists($this->outputDir.'/NotAnEnum.ts'))->toBeFalse()
        ->and(file_exists($this->outputDir.'/InternalOnly.ts'))->toBeFalse();
});

it('renders a string backed enum as an as-const object with a derived union type', function () {
    $this->artisan('enum-objects:generate')->assertExitCode(0);

    expect($this->generated('BrowseSort.ts'))->toBe(<<<'TS'
// Generated by well35/laravel-enum-objects. Do not edit.

export const BrowseSort = {
    Newest: { name: "Newest", value: "newest", label: "Newest" },
    Popular: { name: "Popular", value: "popular", label: "Most played" },
} as const;

export type BrowseSort = (typeof BrowseSort)[keyof typeof BrowseSort]["value"];

TS);
});

it('renders int-backed values unquoted and falls back to headline labels', function () {
    $this->artisan('enum-objects:generate')->assertExitCode(0);

    expect($this->generated('Priority.ts'))
        ->toContain('Low: { name: "Low", value: 1, label: "Low" }')
        ->toContain('VeryHigh: { name: "VeryHigh", value: 10, label: "Very High" }')
        ->not->toContain('Internal');
});

it('uses the case name as value for pure enums and emits a warning', function () {
    $this->artisan('enum-objects:generate')
        ->expectsOutputToContain('pure enum')
        ->assertExitCode(0);

    expect($this->generated('Suit.ts'))
        ->toContain('Hearts: { name: "Hearts", value: "Hearts", label: "Hearts" }');
});

it('merges static and computed properties, case-level winning collisions', function () {
    $this->artisan('enum-objects:generate')->assertExitCode(0);

    expect($this->generated('ItemRarity.ts'))
        ->toContain('color: "#999"')
        ->toContain('color: "#override"')     // case ObjectProperty beats ComputedProperty
        ->toContain('sortWeight: 1')          // ComputedProperty key override
        ->toContain('icon: "sparkle"')
        ->toContain('is_public: true')        // keys are emitted exactly as written
        ->toContain('group: "items"')
        ->toContain('group: "special"')       // case-level beats class-level
        ->toContain('description: "A common item"');
});

it('renders custom base property keys and derives the type from the value key', function () {
    config()->set('enum-objects.name_key', 'key');
    config()->set('enum-objects.value_key', 'id');
    config()->set('enum-objects.label_key', 'text');

    $this->artisan('enum-objects:generate')->assertExitCode(0);

    expect($this->generated('BrowseSort.ts'))
        ->toContain('Newest: { key: "Newest", id: "newest", text: "Newest" }')
        ->toContain('export type BrowseSort = (typeof BrowseSort)[keyof typeof BrowseSort]["id"];');
});

it('omits base properties configured as null', function () {
    config()->set('enum-objects.name_key', null);
    config()->set('enum-objects.label_key', null);

    $this->artisan('enum-objects:generate')->assertExitCode(0);

    expect($this->generated('BrowseSort.ts'))
        ->toContain('Newest: { value: "newest" }')
        ->not->toContain('name:')
        ->not->toContain('label:');
});

it('falls back to the whole case object union when the value key is omitted', function () {
    config()->set('enum-objects.value_key', null);

    $this->artisan('enum-objects:generate')->assertExitCode(0);

    expect($this->generated('BrowseSort.ts'))
        ->toContain('Newest: { name: "Newest", label: "Newest" }')
        ->toContain('export type BrowseSort = (typeof BrowseSort)[keyof typeof BrowseSort];');
});

it('renders json when the format is overridden', function () {
    $this->artisan('enum-objects:generate', ['--format' => 'json'])->assertExitCode(0);

    $decoded = json_decode($this->generated('ItemRarity.json'), associative: true);

    expect($decoded['Legendary'])->toBe([
        'name' => 'Legendary',
        'value' => 'legendary',
        'label' => 'Legendary',
        'group' => 'special',
        'color' => '#override',
        'sortWeight' => 10,
        'icon' => 'sparkle',
    ]);
});

it('prunes only files it previously generated, never foreign files', function () {
    $this->artisan('enum-objects:generate')->assertExitCode(0);

    // hand written files in the output directory are not touched
    file_put_contents($this->outputDir.'/index.ts', 'export * from "./BrowseSort";');

    config()->set('enum-objects.paths', [
        'Well35\\EnumObjects\\Tests\\Fixtures\\Enums\\Items' => __DIR__.'/../Fixtures/Enums/Items',
    ]);

    $this->artisan('enum-objects:generate')->assertExitCode(0);

    expect(file_exists($this->outputDir.'/BrowseSort.ts'))->toBeFalse()      // generated before, pruned
        ->and(file_exists($this->outputDir.'/Items/ItemSlot.ts'))->toBeFalse()
        ->and(file_exists($this->outputDir.'/Items'))->toBeFalse()             // emptied directory removed
        ->and(file_exists($this->outputDir.'/ItemSlot.ts'))->toBeTrue()
        ->and(file_exists($this->outputDir.'/index.ts'))->toBeTrue();          // untouched
});

it('passes --check when in sync and fails on stale, missing, or orphaned files', function () {
    $this->artisan('enum-objects:generate')->assertExitCode(0);
    $this->artisan('enum-objects:generate', ['--check' => true])->assertExitCode(0);

    file_put_contents($this->outputDir.'/BrowseSort.ts', 'tampered');
    $this->artisan('enum-objects:generate', ['--check' => true])->assertExitCode(1);

    $this->artisan('enum-objects:generate')->assertExitCode(0);
    unlink($this->outputDir.'/Priority.ts');
    $this->artisan('enum-objects:generate', ['--check' => true])->assertExitCode(1);

    // foreign files do not fail the check
    $this->artisan('enum-objects:generate')->assertExitCode(0);
    file_put_contents($this->outputDir.'/Orphan.ts', 'export const Orphan = {};');
    $this->artisan('enum-objects:generate', ['--check' => true])->assertExitCode(0);

    // but files the package generated that no longer match an enum do
    config()->set('enum-objects.paths', [
        'Well35\\EnumObjects\\Tests\\Fixtures\\Enums\\Items' => __DIR__.'/../Fixtures/Enums/Items',
    ]);
    $this->artisan('enum-objects:generate', ['--check' => true])->assertExitCode(1);
});

it('prints configured enum directories as json for the vite plugin', function () {
    $this->artisan('enum-objects:generate', ['--paths' => true])
        ->expectsOutputToContain('Fixtures')
        ->assertExitCode(0);

    expect(file_exists($this->outputDir))->toBeFalse(); // --paths generates nothing
});

it('does not report drift for CRLF line endings', function () {
    $this->artisan('enum-objects:generate')->assertExitCode(0);

    $crlf = str_replace("\n", "\r\n", $this->generated('BrowseSort.ts'));
    file_put_contents($this->outputDir.'/BrowseSort.ts', $crlf);

    $this->artisan('enum-objects:generate', ['--check' => true])->assertExitCode(0);
});

it('exposes a one-line sync assertion for host apps', function () {
    $this->artisan('enum-objects:generate')->assertExitCode(0);

    EnumObjects::assertInSync();

    file_put_contents($this->outputDir.'/BrowseSort.ts', 'tampered');

    expect(fn () => EnumObjects::assertInSync())
        ->toThrow(PHPUnit\Framework\AssertionFailedError::class);
});
